# Generated by Django 2.1.1 on 2018-09-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('is_healthy', models.BooleanField(default=False)),
                ('sort_index', models.IntegerField(null=True)),
                ('meal_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_categories.MealCategory')),
            ],
        ),
    ]
