# Generated by Django 2.1.1 on 2018-09-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_items', '0003_auto_20180917_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='meal_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meal_categories.MealCategory'),
        ),
    ]
