# Generated by Django 2.1.1 on 2018-09-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_categories', '0002_auto_20180917_2251'),
        ('meal_items', '0004_auto_20180917_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='meal_category',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='meal_category',
            field=models.ManyToManyField(null=True, to='meal_categories.MealCategory'),
        ),
    ]
