# Generated by Django 2.1.1 on 2018-11-28 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_eatery_name_short'),
        ('meal_items', '0006_auto_20180917_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='meal_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
