# Generated by Django 2.1.1 on 2018-11-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_items', '0007_mealitem_meal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='is_dining_item',
            field=models.BooleanField(default=False),
        ),
    ]
