# Generated by Django 2.1.1 on 2018-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_items', '0009_mealitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
