# Generated by Django 2.1.1 on 2018-09-17 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating_hours', '0003_auto_20180917_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghour',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
