# Generated by Django 2.1.1 on 2018-09-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_eatery_name_short'),
        ('operating_hours', '0004_auto_20180917_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatinghour',
            name='location',
        ),
        migrations.AddField(
            model_name='operatinghour',
            name='location',
            field=models.ManyToManyField(to='locations.Location'),
        ),
    ]
