# Generated by Django 2.1.1 on 2018-11-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_eatery_name_short'),
        ('operating_hours', '0007_auto_20181127_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatinghour',
            name='location',
        ),
        migrations.AddField(
            model_name='operatinghour',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
