# Generated by Django 2.1.1 on 2018-09-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_items.MealItem')),
            ],
        ),
    ]
