# Generated by Django 2.1.1 on 2018-09-15 03:04

from django.db import migrations, models
import meal_photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='liked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=meal_photos.models.upload_image_path),
        ),
    ]
