# Generated by Django 2.1.4 on 2018-12-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_photos', '0002_auto_20180915_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='menu_item',
            new_name='meal_item',
        ),
    ]
