# Generated by Django 2.1.4 on 2018-12-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_reviews', '0003_auto_20181211_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
    ]
