# Generated by Django 2.1.4 on 2018-12-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_reviews', '0004_auto_20181221_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
