# Generated by Django 2.1.4 on 2018-12-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_reviews', '0006_auto_20181222_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='menu_item',
            new_name='meal_item',
        ),
    ]
