# Generated by Django 2.1.1 on 2018-09-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_events', '0002_auto_20180917_2321'),
        ('meal_categories', '0003_auto_20180917_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcategory',
            name='meal_event',
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='meal_event',
            field=models.ManyToManyField(to='meal_events.MealEvent'),
        ),
    ]
