# Generated by Django 2.1.1 on 2018-11-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_events', '0008_auto_20180918_0438'),
        ('meal_categories', '0004_auto_20180917_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcategory',
            name='meal_event',
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='meal_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal_events.MealEvent'),
        ),
    ]
