# Generated by Django 2.1.1 on 2018-09-17 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_events', '0004_auto_20180917_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealevent',
            name='operating_hour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='operating_hours.OperatingHour'),
        ),
    ]
