# Generated by Django 2.1.1 on 2018-09-18 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_events', '0006_auto_20180918_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealevent',
            name='operating_hour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='operating_hours.OperatingHour'),
        ),
    ]
