# Generated by Django 2.1.1 on 2018-09-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='eatery_name_short',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
