# Generated by Django 2.1.1 on 2018-11-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_eatery_name_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='eatery_name',
            field=models.CharField(default='t', max_length=200),
            preserve_default=False,
        ),
    ]
